### ISSUE TITLE
request-parser  consumed http.req's readable streamer

### ISSUE THREAD

**Issue by wangzhenhui1991** [APIDevTools/swagger-express-middleware#77] opened 2016-12-29 07:49 UTC
My proj uesd your swagger-express-middleware and I found http.req's readable streamer has been consumed in request-parser middleware.
```javascript

    router.use(middleware.parseRequest(
        {
            // Configure the cookie parser to use secure cookies
            cookie: {
                secret: 'MySuperSecureSecretKey'
            },
            // Don't allow JSON content over 100kb (default is 1mb)
            json: {
                limit: '100kb'
            },
            // // Change the location for uploaded pet photos (default is the system's temp directory)
            // multipart: {
            //     dest: path.join(__dirname, 'photos')
            // }
        }
    ));
```
So I can't get into the streamer.on('data',function(chunk)) after middleware.parseRequest();
```javascript
            req.on('data', function (chunk) {

                req.bodyChunks.push(chunk);
                console.log('got %d bytes of data', chunk.length);
            });

            req.on('end', function () {
                console.log('bodyParser push chunk...');
                req.rawBody = Buffer.concat(req.bodyChunks);
                req.body = req.rawBody.toString('utf8');
                req.bodySize = req.rawBody.length;

                RequestFormat(req,next);
                next();
            });

```
do you have any suggestion about this conflict?

**Comment by BigstickCarpet** [comment] 2016-12-30 12:00
AFAIK, once the stream has been read, it cannot be read again.  So if you want to be able to consume the stream yourself, then I think the only way to do it is to not use the `parseRequest` middleware at all.

I'll leave this issue open, in case someone can come up with some other idea.

**Comment by wangzhenhui1991** [comment] 2017-01-04 04:20
Thank u for your replay!

**Comment by rkrauskopf** [comment] 2019-02-06 21:44
Closing this issue due to its age. Please re-open it if the issue is still relevant

**Closed by rkrauskopf** 2019-02-06 21:44 UTC
