### ISSUE TITLE
Custom Error Formatting

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [APIDevTools/swagger-express-middleware#111] opened 2018-04-24 13:47 UTC
I am trying to customize the error messages received by the error handler because the provided message example is too long for my use case

*The "dob" query parameter is invalid ("catafd") \n"catafd" is not a properly-formatted date*

When working with the validator *Joi * the error handler received an object with all the properties of the error. Is it possible to send the object to the handler that the Error instance is created from instead of a pre-formatted Error?

**Comment by cdimascio** [comment] 2018-11-18 04:01
This looks like a duplicate of https://github.com/APIDevTools/swagger-express-middleware/issues/79

**Closed** 2024-03-06 17:40 UTC
