### ISSUE TITLE
Question: is there an easy way to work with json API specs?

### ISSUE THREAD

**Issue by jonasbuechel** [APIDevTools/swagger-express-middleware#58] opened 2016-07-01 18:17 UTC
Hi there! First thanks a lot for the great piece of software :)

I'm playing around with it and ask me one big question.
Is it possible to work with the format of [JSON API Specs](http://jsonapi.org/) with this extension? 
Or do I have to customise the source or add some functions to hooks?
Maybe I've overlooked something, or this feature just doesn't exist yet.

According to the examples of jsonapi.org i think there is a difficulty at data storing.
If you compare the POST and GET examples below, you'll see the difference. 
In the POST Request the single object "data" contains the data for itself. 
But for the GET Response, this object is in an array (also named "data).

I've tried two ways:
1. Send Post as below and look at the GET response --> There is no array, single object "data" replaces the storage at each POST
2. At GET response, wrap the single Object with the data array --> works fine for a valid GET response, but then I've to remove the data object at POST which isn't valid according to JSON API

Example for POST:

``` json
POST /photos HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    }
  }
}
```

Example for GET (after 2 POST executions):

``` json
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/photos"
  },
  "data": [{
    "type": "photos",
    "id": "1",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/ember-hamster.png"
    }
  }, {
    "type": "photos",
    "id": "2",
    "attributes": {
      "title": "GitHub Cat",
      "src": "http://example.com/images/github-cat.png"
    }
  }]
}
```

I would be happy if someone just can answer my question. So I know if I'm searching my solution in the right direction :)

Thanks a lot!
Jonas

**Comment by rkrauskopf** [comment] 2019-02-06 21:42
Closing this issue due to its age. Please re-open it if the issue is still relevant

**Closed by rkrauskopf** 2019-02-06 21:42 UTC
