### ISSUE TITLE
URL templates with different placeholder types

### ISSUE THREAD

**Issue by Dunken** [APIDevTools/swagger-express-middleware#36] opened 2016-02-24 07:52 UTC
I have two URL templates:

`/api/series/{id}`  --> `id`is a **string** and uniquely identifies a series
`/api/series/{seriesCollectionId}` --> `seriesCollectionId`is an **integer** and identifies a collection of series

SEM always identifies the first template as the correct one even if a pass a string (SEM doesn't take the type into account). This results is `Error: The "id" path parameter is invalid`

**Comment by rkrauskopf** [comment] 2019-02-06 21:40
Closing this issue due to its age. Please re-open it if the issue is still relevant

**Closed by rkrauskopf** 2019-02-06 21:40 UTC
