### ISSUE TITLE
cannot retrieve all records using GET /, but single record is retrieved /{path-id}

### ISSUE THREAD

**Issue by thinkTank15** [APIDevTools/swagger-express-middleware#69] opened 2016-11-16 20:03 UTC
Hi,
based on sample2, I tried to pre-populate data for my API
 
 
  ```   
    var myDB = new MemoryDataStore();
    myDB.save(
    new Resource('/authorizations/123', {name: xxxx', desc: 'xxxx'}),
    new Resource('/authorizations/456', {name: 'xxxxx', desc: 'xxxx'}),
    new Resource('/authorizations/789', {name: 'xxxx', desc: 'xxxx'}),
    new Resource('/authorizations/100', {name: 'xxxxx', desc: 'xxxx'})
      ); 
```
I am able to retrieve single record when I run a 
` GET /authorizations/123 `
but 
` GET /authorizations ` 
brings back 404. 
While in sample2 `GET /pets` brings back all records.
 In my Spec file, both `/authorizations` and `/authorization/{auth-id}` are of type object. Any ideas what might be causing this?

**Comment by rdewit** [comment] 2016-11-18 03:51
I'm experiencing the same thing where I've got a spec file that tries to follow the JSON API spec (i.e. return an object instead of array for collections). No solution yet though (may have to trawl through the code to find out where things fall over).
If you do find a solution, please report back!

**Comment by simar15** [comment] 2016-11-18 04:14
@rdewit , you're right. Object is treated as resource hence it does not work.
Will let you know if I find some way around.

**Comment by BigstickCarpet** [comment] 2016-11-24 21:19
@simar15 @rdewit - I don't have time to look into this right now, but the behavior is [documented here](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#default-behavior), which may be usueful to you.  Specifically, [Step 1 (Determine if it's a collection or resource operation)](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#1-determine-if-its-a-collection-or-resource-operation)

**Comment by z-ax** [comment] 2017-11-06 15:13
Looks like having the same issue here and don't see the the easy way to make it work automatically. An example would be helpful - trying to not consider an option to mock all collections manually.

**Comment by rkrauskopf** [comment] 2019-02-06 21:38
Closing this issue due to its age. Please re-open it if the issue is still relevant

**Closed by rkrauskopf** 2019-02-06 21:38 UTC
