### ISSUE TITLE
error.status does not always return

### ISSUE THREAD

**Issue by liront2** [APIDevTools/swagger-express-middleware#88] opened 2017-06-26 13:52 UTC
Hi

We noticed that only error.message returns when the following occurs.
Here's a part of a Swagger.yaml file used in our package:

`  ThreeDSecure:
    description: "Three D secure attributes."
    required:
      - encoding
      - xid
      - cavv
      - eci_flag
    properties:
      encoding:
        type: string
      xid:
        type: string
      cavv:
        type: string
      eci_flag:
        type: string`

Now, ThreeDSecure is an object holding Strings inside.
If a request is sent to an instance based on this Swagger, AND the request.ThreeDSecure=null AND one of its child fields is required, error.status will NOT return, only error.message.

Here's a detailed StackTrace:

`Cannot read property 'encoding' of null\n    at ono (/usr/src/app/node_modules/ono/lib/index.js:62:17)\n    at parseParameter (/usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:146:11)\n    at /usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:93:18\n    at Array.some (native)\n    at parseBodyParam (/usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:77:10)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at parseFormDataParams (/usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:68:3)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at parseSimpleParams (/usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:46:3)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at /usr/src/app/node_modules/multer/index.js:218:19\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at rawParser (/usr/src/app/node_modules/body-parser/lib/types/raw.js:58:7)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at urlencodedParser (/usr/src/app/node_modules/body-parser/lib/types/urlencoded.js:82:7)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at textParser (/usr/src/app/node_modules/body-parser/lib/types/text.js:60:7)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at /usr/src/app/node_modules/body-parser/lib/read.js:130:5\n    at invokeCallback (/usr/src/app/node_modules/raw-body/index.js:262:16)\n    at done (/usr/src/app/node_modules/raw-body/index.js:251:7)\n    at IncomingMessage.onEnd (/usr/src/app/node_modules/raw-body/index.js:307:7)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9) \n\nTypeError: Cannot read property 'encoding' of null\n    at /usr/src/app/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:509:20\n    at /usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3073:15\n    at baseForOwn (/usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:2046:14)\n    at /usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3043:18\n    at Function.<anonymous> (/usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3346:13)\n    at parseObject (/usr/src/app/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:508:5)\n    at JsonSchema.parse (/usr/src/app/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:92:14)\n    at /usr/src/app/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:512:42\n    at /usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3073:15\n    at baseForOwn (/usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:2046:14)\n    at /usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3043:18\n    at Function.<anonymous> (/usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3346:13)\n    at parseObject (/usr/src/app/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:508:5)\n    at JsonSchema.parse (/usr/src/app/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:92:14)\n    at /usr/src/app/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:512:42\n    at /usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3073:15\n    at baseForOwn (/usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:2046:14)\n    at /usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3043:18\n    at Function.<anonymous> (/usr/src/app/node_modules/swagger-express-middleware/node_modules/lodash/index.js:3346:13)\n    at parseObject (/usr/src/app/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:508:5)\n    at JsonSchema.parse (/usr/src/app/node_modules/swagger-express-middleware/lib/helpers/json-schema.js:92:14)\n    at parseParameter (/usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:143:35)\n    at /usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:93:18\n    at Array.some (native)\n    at parseBodyParam (/usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:77:10)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at parseFormDataParams (/usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:68:3)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at parseSimpleParams (/usr/src/app/node_modules/swagger-express-middleware/lib/param-parser.js:46:3)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at /usr/src/app/node_modules/multer/index.js:218:19\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at rawParser (/usr/src/app/node_modules/body-parser/lib/types/raw.js:58:7)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at urlencodedParser (/usr/src/app/node_modules/body-parser/lib/types/urlencoded.js:82:7)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at textParser (/usr/src/app/node_modules/body-parser/lib/types/text.js:60:7)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at /usr/src/app/node_modules/body-parser/lib/read.js:130:5\n    at invokeCallback (/usr/src/app/node_modules/raw-body/index.js:262:16)\n    at done (/usr/src/app/node_modules/raw-body/index.js:251:7)\n    at IncomingMessage.onEnd (/usr/src/app/node_modules/raw-body/index.js:307:7)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)`

Please check and fix the issue :)

Liron

**Comment by rkrauskopf** [comment] 2019-02-06 21:35
Closing this issue due to its age. Please re-open it if the issue is still relevant

**Closed by rkrauskopf** 2019-02-06 21:35 UTC
