### ISSUE TITLE
Correct handling of paths when `basePath` is set in Swagger definition

### ISSUE THREAD

**Issue by philgs** [APIDevTools/swagger-express-middleware#13] opened 2015-08-26 13:09 UTC
In my Swagger 2.0 definition, I have

``` yaml
basePath: /api

paths:
  /spinners:
    get: ...
  /spinners/{id}
    parameters: ...
    get: ...
```

When I do `GET http://localhost:3000/api/spinners/0`, I receive a 404. 

If I comment out the `basePath` line in the definition, then do `GET http://localhost:3000/spinners/0`, I get the JSON data for the object (as I've set it in the mocks and datastore).

Based on the debug output, it is parsing the path correctly. However, when it calls `get` on the datastore, it seems to be passing the full path, `/api/spinners/0` as the `resource` parameter to `DataStore.get`, instead of removing the base path first.

This is in version 0.4.7, which is the most recent in NPM.

**Comment by BigstickCarpet** [comment] 2015-08-27 00:00
Question... why not just add the data to the DataStore at the full path (including the basePath)?  For example:

```javascript
dataStore.save(new Resource('/api/spinners/0', {...}));
```

Stripping-off the basePath seems less flexible and potentially confusing.  Doesn't it make more sense for the Resource URL to match the _full_ request path?

**Comment by imZack** [comment] 2016-01-27 08:09
Oops, just dump into the same issue here.
It's worth when someone just don't want to write any JS code like `dataStore.save(new Resource('/api/spinners/0', {...}));` I think it would be better to support `basePath` as in Swagger docs.

Btw, thanks @BigstickCarpet for bringing this awesome middleware for us. :+1:

**Comment by rkrauskopf** [comment] 2019-02-06 21:36
Closing this issue due to its age. Please re-open it if the issue is still relevant

**Closed by rkrauskopf** 2019-02-06 21:36 UTC
