### ISSUE TITLE
why the response include request data

### ISSUE THREAD

**Issue by wstygk** [APIDevTools/swagger-express-middleware#82] opened 2017-03-29 14:36 UTC
my response data include the  request data ,it's strange, why?

**Comment by BigstickCarpet** [comment] 2017-03-30 14:32
Please see [the documentation](https://github.com/BigstickCarpet/swagger-express-middleware/blob/master/docs/middleware/mock.md#default-behavior) for an explanation of the default behavior of the Mock middleware, and how to customize that behavior

**Comment by rkrauskopf** [comment] 2019-02-06 21:45
Closing this issue due to its age. Please re-open it if the issue is still relevant

**Closed by rkrauskopf** 2019-02-06 21:45 UTC
