### ISSUE TITLE
submodules

### ISSUE THREAD

**Issue by xunxky** [APIDevTools/swagger-express-middleware#70] opened 2016-11-29 21:28 UTC
hi i am having trouble applying swagger-express to my application with submodules. 

apparently the metadata is not including req.baseUrl when calculation their position (or respectively using originalUrl instead)

**Comment by rkrauskopf** [comment] 2019-02-06 21:38
Closing this issue due to its age. Please re-open it if the issue is still relevant

**Closed by rkrauskopf** 2019-02-06 21:38 UTC
